#!/bin/bash
set -e

unset BUNDLE_GEMFILE
export RAILS_ENV=development
port=2134

while getopts ":p:" opt; do
  case $opt in
    p)
      port="$OPTARG"
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
  esac
done

cd sorcery
bundle check || bundle install

exec bundle exec ruby app.rb -p $port
